## Messy_Employee_Dataset

### Import Libraries

In [1]:
import pandas as pd

## Load Dataset

In [2]:
df=pd.read_excel('Messy_Employee_dataset.xlsx')
df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

In [3]:
#Display first five rows
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [4]:
#display last five rows
df.tail()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

In [5]:
#check dataset shape
df.shape

(1020, 12)

In [6]:
#describe the dataset
df.describe()

              Age         Salary         Phone
count  809.000000     996.000000  1.020000e+03
mean    32.484549   85155.056396 -4.942253e+09
std      5.656860   19873.727918  2.817326e+09
min     25.000000   50047.320000 -9.994973e+09
25%     25.000000   68392.487500 -7.341992e+09
50%     30.000000   85547.870000 -4.943997e+09
75%     40.000000  100974.027500 -2.520391e+09
max     40.000000  119971.650000 -3.896086e+06

In [7]:
#check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [11]:
#Convert Join_Date to datetime
df['Join_Date']=pd.to_datetime(df['Join_Date'],errors='coerce',format='%d-%m-%Y')
df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,2023-08-19,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,-7629745492,Average,False

In [14]:
#Split 'Department_Region' into 'Department' and 'Region'
df[['Department', 'Region']] = df['Department_Region'].str.split('-', expand=True)
df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,-1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,2023-08-19,NaN,david.miller@example.com,-3546212759,Good,True,HR,California
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,-2508261122,Good,True,Cloud Tech,Texas
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,-1261632487,Average,False,Finance,New York
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,-8995729892,Good,True,HR,Florida
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,-7629745492,Average,False,DevOps,Illinois

In [15]:
# Handle missing values (Impute with Median)
df['Age'] = df['Age'].fillna(df['Age'].median()).astype(int)
df['Salary'] = df['Salary'].fillna(df['Salary'].median())
df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,-1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30,HR-California,Active,2023-08-19,85547.87,david.miller@example.com,-3546212759,Good,True,HR,California
1016,EMP2016,David,Johnson,30,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,-2508261122,Good,True,Cloud Tech,Texas
1017,EMP2017,Charlie,Williams,40,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,-1261632487,Average,False,Finance,New York
1018,EMP2018,Alice,Garcia,30,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,-8995729892,Good,True,HR,Florida
1019,EMP2019,Heidi,Jones,30,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,-7629745492,Average,False,DevOps,Illinois

In [16]:
# Check for duplicate rows
print("Duplicate rows count:", df.duplicated().sum())
df

Duplicate rows count: 0

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,-1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30,HR-California,Active,2023-08-19,85547.87,david.miller@example.com,-3546212759,Good,True,HR,California
1016,EMP2016,David,Johnson,30,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,-2508261122,Good,True,Cloud Tech,Texas
1017,EMP2017,Charlie,Williams,40,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,-1261632487,Average,False,Finance,New York
1018,EMP2018,Alice,Garcia,30,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,-8995729892,Good,True,HR,Florida
1019,EMP2019,Heidi,Jones,30,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,-7629745492,Average,False,DevOps,Illinois

In [18]:
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                1020 non-null   int64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   datetime64[ns]
 7   Salary             1020 non-null   float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
 12  Department         1020 non-null   object
 13  Region             1020 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 104.7+ KB

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,-1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30,HR-California,Active,2023-08-19,85547.87,david.miller@example.com,-3546212759,Good,True,HR,California
1016,EMP2016,David,Johnson,30,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,-2508261122,Good,True,Cloud Tech,Texas
1017,EMP2017,Charlie,Williams,40,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,-1261632487,Average,False,Finance,New York
1018,EMP2018,Alice,Garcia,30,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,-8995729892,Good,True,HR,Florida
1019,EMP2019,Heidi,Jones,30,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,-7629745492,Average,False,DevOps,Illinois

In [19]:
# Fix Phone column: convert to positive string numbers
df['Phone'] = df['Phone'].abs().astype(str)
df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30,HR-California,Active,2023-08-19,85547.87,david.miller@example.com,3546212759,Good,True,HR,California
1016,EMP2016,David,Johnson,30,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,2508261122,Good,True,Cloud Tech,Texas
1017,EMP2017,Charlie,Williams,40,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,1261632487,Average,False,Finance,New York
1018,EMP2018,Alice,Garcia,30,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,8995729892,Good,True,HR,Florida
1019,EMP2019,Heidi,Jones,30,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,7629745492,Average,False,DevOps,Illinois

In [20]:
#  Drop the redundant combined column
df.drop(columns=['Department_Region'], inplace=True)
df

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30,Active,2023-08-19,85547.87,david.miller@example.com,3546212759,Good,True,HR,California
1016,EMP2016,David,Johnson,30,Inactive,2021-11-07,100215.06,david.johnson@example.com,2508261122,Good,True,Cloud Tech,Texas
1017,EMP2017,Charlie,Williams,40,Active,2023-10-04,114587.11,charlie.williams@example.com,1261632487,Average,False,Finance,New York
1018,EMP2018,Alice,Garcia,30,Inactive,2024-12-16,71318.79,alice.garcia@example.com,8995729892,Good,True,HR,Florida
1019,EMP2019,Heidi,Jones,30,Pending,2021-02-22,77764.24,heidi.jones@example.com,7629745492,Average,False,DevOps,Illinois

In [22]:
# 3. Create a clean Full_Name column 
df['Full_Name'] = df['First_Name'] + ' ' + df['Last_Name']
df

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region,Full_Name
0,EMP1000,Bob,Davis,25,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California,Bob Davis
1,EMP1001,Bob,Brown,30,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas,Bob Brown
2,EMP1002,Alice,Jones,30,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada,Alice Jones
3,EMP1003,Eva,Davis,25,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada,Eva Davis
4,EMP1004,Frank,Williams,25,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida,Frank Williams
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30,Active,2023-08-19,85547.87,david.miller@example.com,3546212759,Good,True,HR,California,David Miller
1016,EMP2016,David,Johnson,30,Inactive,2021-11-07,100215.06,david.johnson@example.com,2508261122,Good,True,Cloud Tech,Texas,David Johnson
1017,EMP2017,Charlie,Williams,40,Active,2023-10-04,114587.11,charlie.williams@example.com,1261632487,Average,False,Finance,New York,Charlie Williams
1018,EMP2018,Alice,Garcia,30,Inactive,2024-12-16,71318.79,alice.garcia@example.com,8995729892,Good,True,HR,Florida,Alice Garcia
1019,EMP2019,Heidi,Jones,30,Pending,2021-02-22,77764.24,heidi.jones@example.com,7629745492,Average,False,DevOps,Illinois,Heidi Jones

In [23]:
from sqlalchemy import create_engine

#  Enter MySQL details
user = 'root'
password = 'Root#1234'  # <--- Replace with your actual MySQL password
host = 'localhost'
port = '3306'
database = 'employee_db'

In [24]:
# Create the connection engine
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

In [25]:
#  Upload DataFrame to MySQL table 'clean_employees'
df.to_sql(name='clean_employees', con=engine, if_exists='replace', index=False)

1020